/**
 * POS Service Manager - Multi-Tenant Version
 * Unified interface for all POS providers
 * WOLF HMS - Multi-Provider POS Integration
 */

const { pool } = require('../../db');

// Import adapters
const PineLabsAdapter = require('./adapters/PineLabsAdapter');
const PaytmAdapter = require('./adapters/PaytmAdapter');
const RazorpayPOSAdapter = require('./adapters/RazorpayPOSAdapter');
const PhonePeAdapter = require('./adapters/PhonePeAdapter');
const MswipeAdapter = require('./adapters/MswipeAdapter');
const WorldlineAdapter = require('./adapters/WorldlineAdapter');

class POSServiceManager {
    constructor() { this.adapters = new Map(); this.initialized = false; }

    async initialize() { if (this.initialized) return; this.registerAdapter('pine_labs', new PineLabsAdapter()); this.registerAdapter('paytm', new PaytmAdapter()); this.registerAdapter('razorpay', new RazorpayPOSAdapter()); this.registerAdapter('phonepe', new PhonePeAdapter()); this.registerAdapter('mswipe', new MswipeAdapter()); this.registerAdapter('worldline', new WorldlineAdapter()); for (const [code, adapter] of this.adapters) { try { const credentials = await this.getCredentials(code); if (credentials && Object.keys(credentials).length > 0) await adapter.initialize(credentials); } catch (error) { console.warn(`Failed to initialize ${code} adapter:`, error.message); } } this.initialized = true; console.log('[POSServiceManager] Initialized with', this.adapters.size, 'adapters'); }

    registerAdapter(providerCode, adapter) { this.adapters.set(providerCode, adapter); }
    getAdapter(providerCode) { const adapter = this.adapters.get(providerCode); if (!adapter) throw new Error(`Unknown POS provider: ${providerCode}`); return adapter; }

    async getCredentials(providerCode, hospitalId = null) { try { let query = `SELECT c.credential_key, c.credential_value_encrypted, c.is_production FROM pos_credentials c JOIN pos_providers p ON c.provider_id = p.id WHERE p.code = $1`; const params = [providerCode]; if (hospitalId) { query += ` AND (c.hospital_id = $2 OR c.hospital_id IS NULL)`; params.push(hospitalId); } const result = await pool.query(query, params); const credentials = {}; result.rows.forEach(row => { credentials[row.credential_key] = row.credential_value_encrypted; credentials.isProduction = row.is_production; }); return credentials; } catch (error) { console.warn(`No credentials found for ${providerCode}`); return {}; } }

    // Provider Management (shared global data)
    async getProviders() { const result = await pool.query(`SELECT id, code, name, logo_url, website_url, features, is_active FROM pos_providers ORDER BY name`); return result.rows; }
    async getActiveProviders() { const result = await pool.query(`SELECT id, code, name, logo_url, features FROM pos_providers WHERE is_active = true ORDER BY name`); return result.rows; }
    async getProviderByCode(code) { const result = await pool.query(`SELECT * FROM pos_providers WHERE code = $1`, [code]); return result.rows[0]; }

    // Device Management - Multi-Tenant
    async getDevices(hospitalId, filters = {}) { let query = `SELECT d.*, p.name as provider_name, p.code as provider_code, p.logo_url as provider_logo FROM pos_devices d JOIN pos_providers p ON d.provider_id = p.id WHERE (d.hospital_id = $1 OR d.hospital_id IS NULL)`; const params = [hospitalId]; if (filters.status) { params.push(filters.status); query += ` AND d.status = $${params.length}`; } if (filters.department) { params.push(filters.department); query += ` AND d.department = $${params.length}`; } if (filters.location) { params.push(`%${filters.location}%`); query += ` AND d.location ILIKE $${params.length}`; } if (filters.provider) { params.push(filters.provider); query += ` AND p.code = $${params.length}`; } query += ` ORDER BY d.location, d.device_name`; const result = await pool.query(query, params); return result.rows; }

    async getDevice(deviceId, hospitalId = null) { let query = `SELECT d.*, p.name as provider_name, p.code as provider_code FROM pos_devices d JOIN pos_providers p ON d.provider_id = p.id WHERE (d.id = $1 OR d.device_id = $1)`; const params = [deviceId]; if (hospitalId) { query += ` AND (d.hospital_id = $2 OR d.hospital_id IS NULL)`; params.push(hospitalId); } const result = await pool.query(query, params); return result.rows[0]; }

    async registerDevice(deviceData, hospitalId) { const { device_name, provider_code, terminal_id, merchant_id, location, department, connection_type, ip_address, registered_by } = deviceData; const provider = await this.getProviderByCode(provider_code); if (!provider) throw new Error(`Unknown provider: ${provider_code}`); const device_id = `DEV-${Date.now()}-${Math.random().toString(36).substr(2, 4).toUpperCase()}`; const result = await pool.query(`INSERT INTO pos_devices (device_id, device_name, provider_id, terminal_id, merchant_id, location, department, connection_type, ip_address, registered_by, hospital_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING *`, [device_id, device_name, provider.id, terminal_id, merchant_id, location, department, connection_type || 'cloud', ip_address, registered_by, hospitalId]); return result.rows[0]; }

    async updateDevice(deviceId, updates, hospitalId) { const allowedFields = ['device_name', 'terminal_id', 'merchant_id', 'location', 'department', 'connection_type', 'ip_address', 'status', 'daily_limit', 'single_txn_limit', 'auto_settlement_time']; const fields = []; const values = []; let paramIndex = 1; for (const [key, value] of Object.entries(updates)) { if (allowedFields.includes(key)) { fields.push(`${key} = $${paramIndex}`); values.push(value); paramIndex++; } } if (fields.length === 0) throw new Error('No valid fields to update'); fields.push(`updated_at = NOW()`); values.push(deviceId); values.push(hospitalId); const result = await pool.query(`UPDATE pos_devices SET ${fields.join(', ')} WHERE id = $${paramIndex} AND (hospital_id = $${paramIndex + 1} OR hospital_id IS NULL) RETURNING *`, values); return result.rows[0]; }

    async testConnection(deviceId, hospitalId) { const device = await this.getDevice(deviceId, hospitalId); if (!device) throw new Error('Device not found'); const adapter = this.getAdapter(device.provider_code); const result = await adapter.testConnection(device); await pool.query(`UPDATE pos_devices SET last_heartbeat = NOW() WHERE id = $1`, [device.id]); return result; }

    // Transaction Processing - Multi-Tenant
    async initiatePayment(deviceId, invoiceId, amount, hospitalId, options = {}) { const device = await this.getDevice(deviceId, hospitalId); if (!device) throw new Error('Device not found'); const adapter = this.getAdapter(device.provider_code); const transactionId = `POS${Date.now()}${Math.random().toString(36).substr(2, 6).toUpperCase()}`; const txnResult = await pool.query(`INSERT INTO pos_transactions (transaction_id, device_id, provider_id, invoice_id, amount, total_amount, payment_mode, status, initiated_by, department, counter_number, hospital_id) VALUES ($1, $2, $3, $4, $5, $5, $6, 'initiated', $7, $8, $9, $10) RETURNING *`, [transactionId, device.id, device.provider_id, invoiceId, amount, options.paymentMode || 'card', options.initiatedBy, device.department, device.counter_number, hospitalId]); try { const providerResult = await adapter.initiatePayment(device, invoiceId, amount, options); await pool.query(`UPDATE pos_transactions SET provider_txn_id = $1, request_payload = $2 WHERE id = $3`, [providerResult.providerTxnId, JSON.stringify(options), txnResult.rows[0].id]); return { transactionId, providerTxnId: providerResult.providerTxnId, status: 'initiated', message: providerResult.message || 'Payment initiated on terminal', qrCode: providerResult.qrCode }; } catch (error) { await pool.query(`UPDATE pos_transactions SET status = 'failed', failure_reason = $1 WHERE id = $2`, [error.message, txnResult.rows[0].id]); throw error; } }

    async checkStatus(transactionId, hospitalId) { const txn = await this.getTransaction(transactionId, hospitalId); if (!txn) throw new Error('Transaction not found'); if (['success', 'failed', 'cancelled'].includes(txn.status)) return txn; const adapter = this.getAdapter(txn.provider_code); const providerStatus = await adapter.checkStatus(txn.provider_txn_id); await pool.query(`UPDATE pos_transactions SET status = $1, response_code = $2, response_message = $3, card_type = $4, card_last_four = $5, auth_code = $6, rrn = $7, response_payload = $8, completed_at = CASE WHEN $1 IN ('success', 'failed') THEN NOW() ELSE completed_at END WHERE id = $9`, [providerStatus.status, providerStatus.responseCode, providerStatus.responseMessage, providerStatus.cardType, providerStatus.cardLastFour, providerStatus.authCode, providerStatus.rrn, JSON.stringify(providerStatus.raw), txn.id]); return { ...txn, ...providerStatus }; }

    async getTransaction(transactionId, hospitalId = null) { let query = `SELECT t.*, p.code as provider_code, p.name as provider_name, d.device_name, d.location FROM pos_transactions t JOIN pos_providers p ON t.provider_id = p.id JOIN pos_devices d ON t.device_id = d.id WHERE (t.id = $1 OR t.transaction_id = $1 OR t.provider_txn_id = $1)`; const params = [transactionId]; if (hospitalId) { query += ` AND (t.hospital_id = $2 OR t.hospital_id IS NULL)`; params.push(hospitalId); } const result = await pool.query(query, params); return result.rows[0]; }

    async cancelPayment(transactionId, hospitalId) { const txn = await this.getTransaction(transactionId, hospitalId); if (!txn) throw new Error('Transaction not found'); if (txn.status !== 'initiated' && txn.status !== 'pending') throw new Error(`Cannot cancel transaction with status: ${txn.status}`); const adapter = this.getAdapter(txn.provider_code); const result = await adapter.cancel(txn.provider_txn_id); await pool.query(`UPDATE pos_transactions SET status = 'cancelled', cancelled_at = NOW() WHERE id = $1`, [txn.id]); return result; }

    async initiateRefund(transactionId, hospitalId, amount = null, reason = '') { const txn = await this.getTransaction(transactionId, hospitalId); if (!txn) throw new Error('Transaction not found'); if (txn.status !== 'success') throw new Error('Can only refund successful transactions'); const refundAmount = amount || txn.total_amount; const adapter = this.getAdapter(txn.provider_code); const result = await adapter.refund(txn.provider_txn_id, refundAmount, reason); await pool.query(`INSERT INTO pos_refunds (refund_id, original_txn_id, amount, reason, status, hospital_id) VALUES ($1, $2, $3, $4, 'initiated', $5)`, [result.refundId, txn.id, refundAmount, reason, hospitalId]); return result; }

    // EMI Support - Multi-Tenant
    async getEMIOffers(deviceId, amount, hospitalId, cardBin = null) { const device = await this.getDevice(deviceId, hospitalId); if (!device) throw new Error('Device not found'); const adapter = this.getAdapter(device.provider_code); if (typeof adapter.getEMIOffers !== 'function') return []; const offers = await adapter.getEMIOffers(amount, cardBin); return offers.map(offer => ({ ...offer, provider: device.provider_code, providerName: device.provider_name })); }

    async getAllEMIOffers(amount, hospitalId, cardBin = null) { const devices = await this.getDevices(hospitalId, { status: 'active' }); const allOffers = []; for (const device of devices) { try { const adapter = this.getAdapter(device.provider_code); if (typeof adapter.getEMIOffers === 'function') { const offers = await adapter.getEMIOffers(amount, cardBin); offers.forEach(offer => { allOffers.push({ ...offer, deviceId: device.id, deviceName: device.device_name, provider: device.provider_code, providerName: device.provider_name }); }); } } catch (error) { console.warn(`Failed to get EMI offers from ${device.device_name}:`, error.message); } } return allOffers.sort((a, b) => a.interestRate - b.interestRate); }

    // Settlement - Multi-Tenant
    async initiateSettlement(deviceId, hospitalId, initiatedBy = null) { const device = await this.getDevice(deviceId, hospitalId); if (!device) throw new Error('Device not found'); const adapter = this.getAdapter(device.provider_code); const result = await adapter.settlement(device.terminal_id); const settlementId = `SETT${Date.now()}`; await pool.query(`INSERT INTO pos_settlements (settlement_id, device_id, provider_id, batch_id, settlement_date, total_sale_count, total_sale_amount, net_amount, status, initiated_by, hospital_id) VALUES ($1, $2, $3, $4, CURRENT_DATE, $5, $6, $6, 'pending', $7, $8)`, [settlementId, device.id, device.provider_id, result.batchId, result.transactionCount, result.totalAmount, initiatedBy, hospitalId]); await pool.query(`UPDATE pos_devices SET last_settlement_at = NOW() WHERE id = $1`, [device.id]); return { settlementId, ...result }; }

    // Reports - Multi-Tenant
    async getTransactionReport(hospitalId, filters = {}) { let query = `SELECT t.transaction_id, t.amount, t.status, t.payment_mode, t.card_type, t.card_last_four, t.auth_code, t.rrn, t.initiated_at, t.completed_at, p.name as provider_name, d.device_name, d.location, d.department, i.invoice_number FROM pos_transactions t JOIN pos_providers p ON t.provider_id = p.id JOIN pos_devices d ON t.device_id = d.id LEFT JOIN invoices i ON t.invoice_id = i.id WHERE (t.hospital_id = $1 OR t.hospital_id IS NULL)`; const params = [hospitalId]; if (filters.startDate) { params.push(filters.startDate); query += ` AND t.initiated_at >= $${params.length}`; } if (filters.endDate) { params.push(filters.endDate); query += ` AND t.initiated_at <= $${params.length}`; } if (filters.provider) { params.push(filters.provider); query += ` AND p.code = $${params.length}`; } if (filters.status) { params.push(filters.status); query += ` AND t.status = $${params.length}`; } if (filters.device) { params.push(filters.device); query += ` AND d.id = $${params.length}`; } query += ` ORDER BY t.initiated_at DESC LIMIT 500`; const result = await pool.query(query, params); return result.rows; }

    async getDailySummary(hospitalId, date = null) { const targetDate = date || new Date().toISOString().split('T')[0]; const result = await pool.query(`SELECT p.code as provider_code, p.name as provider_name, COUNT(*) as total_transactions, COUNT(CASE WHEN t.status = 'success' THEN 1 END) as successful, COUNT(CASE WHEN t.status = 'failed' THEN 1 END) as failed, SUM(CASE WHEN t.status = 'success' THEN t.total_amount ELSE 0 END) as total_amount FROM pos_transactions t JOIN pos_providers p ON t.provider_id = p.id WHERE DATE(t.initiated_at) = $1 AND (t.hospital_id = $2 OR t.hospital_id IS NULL) GROUP BY p.id, p.code, p.name`, [targetDate, hospitalId]); return result.rows; }
}

let posServiceInstance = null;
const getPOSService = async () => { if (!posServiceInstance) { posServiceInstance = new POSServiceManager(); await posServiceInstance.initialize(); } return posServiceInstance; };

module.exports = { POSServiceManager, getPOSService };
