-- Phase 11: Radiology Information System (RIS) Schema
-- Separation from Lab Requests to support DICOM/PACS
CREATE TABLE IF NOT EXISTS radiology_orders (
    id SERIAL PRIMARY KEY,
    hospital_id INTEGER REFERENCES hospitals(id),
    patient_id UUID REFERENCES patients(id),
    visit_id INTEGER REFERENCES opd_visits(id),
    -- Nullable (Direct Walk-in)
    admission_id INTEGER REFERENCES admissions(id),
    -- Nullable (OPD)
    -- DICOM Essential Keys
    accession_number VARCHAR(50) UNIQUE NOT NULL,
    -- The "Link" to the machine (0008,0050)
    modality VARCHAR(10) NOT NULL,
    -- CT, MR, XA, US, CR (0008,0060)
    study_instance_uid VARCHAR(100),
    -- Generated by Modality after scan (0020,000D)
    -- Workflow
    status VARCHAR(20) DEFAULT 'Scheduled',
    -- Scheduled, In-Progress, Completed, Reported, Cancelled
    priority VARCHAR(10) DEFAULT 'Routine',
    -- Routine, Stat (Emergency)
    -- Clinical Data
    study_description TEXT,
    -- "CT Brain Plain" (0008,1030)
    clinical_history TEXT,
    -- "Headache for 3 days" (0010,21B0)
    scheduled_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    performed_date TIMESTAMP,
    -- Results
    report_content TEXT,
    -- Markdown/Text Report
    pacs_link TEXT,
    -- URL to Orthanc/OHIF
    radiologist_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- Indexes for MWL Query Performance
CREATE INDEX idx_ris_accession ON radiology_orders(accession_number);
CREATE INDEX idx_ris_status ON radiology_orders(status);
CREATE INDEX idx_ris_scheduled ON radiology_orders(scheduled_date);
CREATE INDEX idx_ris_hospital ON radiology_orders(hospital_id);
-- Migration: Move existing X-Ray/CT from lab_requests to radiology_orders is complex 
-- because lab_requests uses integer patient_id in some versions? 
-- No, patients.id is UUID in recent updates.
-- We will leave legacy data in lab_requests and start fresh for "Modern Radiology".