-- ============================================
-- PMJAY HBP 2.0 Seed Data
-- Priority Specialties: General Medicine, Nephrology, 
-- Ophthalmology, Obstetrics, General Surgery
-- Based on claim volume research (~21% of total claims)
-- ============================================
BEGIN;
-- ============================================
-- SPECIALTIES (23 total, seeding priority ones)
-- ============================================
INSERT INTO pmjay_specialties (code, name, procedure_count)
VALUES ('MG', 'General Medicine', 150),
    ('MC', 'Cardiology', 45),
    ('NE', 'Nephrology', 25),
    ('OP', 'Ophthalmology', 40),
    ('OG', 'Obstetrics & Gynaecology', 85),
    ('GS', 'General Surgery', 120),
    ('OR', 'Orthopedics', 90),
    ('UR', 'Urology', 55),
    ('NS', 'Neurosurgery', 60),
    ('CT', 'Cardiothoracic Surgery', 35),
    ('PE', 'Pediatric Medical', 45),
    ('PS', 'Pediatric Surgery', 40),
    ('EN', 'ENT', 50),
    ('DE', 'Dermatology', 20),
    ('PM', 'Plastic Surgery', 30),
    ('ON', 'Oncology', 75),
    ('BU', 'Burns', 25),
    ('EM', 'Emergency Medicine', 30),
    ('PU', 'Pulmonology', 35),
    ('GE', 'Gastroenterology', 40),
    ('RH', 'Rheumatology', 15),
    ('NR', 'Neurology', 30),
    ('IC', 'Intensive Care', 10) ON CONFLICT (code) DO
UPDATE
SET name = EXCLUDED.name,
    procedure_count = EXCLUDED.procedure_count;
-- ============================================
-- PACKAGES - General Medicine (High Volume)
-- ============================================
INSERT INTO pmjay_packages (
        code,
        name,
        specialty_code,
        base_rate,
        tier1_rate,
        tier2_rate,
        requires_preauth,
        expected_los,
        is_surgical,
        is_daycare,
        hbp_version
    )
VALUES -- Medical Packages
    (
        'MG001',
        'Acute Febrile Illness',
        'MG',
        1800,
        2000,
        1600,
        FALSE,
        3,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG002',
        'Acute Gastroenteritis with dehydration',
        'MG',
        2000,
        2200,
        1800,
        FALSE,
        3,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG003',
        'Dengue Fever - Moderate',
        'MG',
        3000,
        3500,
        2700,
        FALSE,
        4,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG004',
        'Dengue Fever - Severe (DHF/DSS)',
        'MG',
        8000,
        9000,
        7000,
        TRUE,
        5,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG005',
        'Typhoid Fever',
        'MG',
        2500,
        3000,
        2200,
        FALSE,
        5,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG006',
        'Malaria - Uncomplicated',
        'MG',
        2000,
        2200,
        1800,
        FALSE,
        3,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG007',
        'Malaria - Severe/Complicated',
        'MG',
        6000,
        7000,
        5500,
        TRUE,
        5,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG008',
        'Pneumonia - Community Acquired',
        'MG',
        4000,
        4500,
        3500,
        FALSE,
        5,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG009',
        'Pneumonia - Severe/ICU',
        'MG',
        12000,
        14000,
        10000,
        TRUE,
        7,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG010',
        'Acute Asthma/COPD Exacerbation',
        'MG',
        3500,
        4000,
        3000,
        FALSE,
        4,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG011',
        'Cellulitis',
        'MG',
        2500,
        3000,
        2200,
        FALSE,
        4,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG012',
        'UTI - Complicated',
        'MG',
        3000,
        3500,
        2700,
        FALSE,
        4,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG013',
        'Diabetic Ketoacidosis',
        'MG',
        8000,
        9000,
        7000,
        TRUE,
        5,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG014',
        'Stroke - Acute Management (Non-thrombolysis)',
        'MG',
        10000,
        12000,
        8000,
        TRUE,
        7,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG015',
        'Heart Failure - Acute Decompensated',
        'MG',
        8000,
        9000,
        7000,
        TRUE,
        5,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG016',
        'Snake Bite - without AVS',
        'MG',
        2000,
        2500,
        1800,
        FALSE,
        3,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG017',
        'Snake Bite - with AVS',
        'MG',
        6000,
        7000,
        5500,
        FALSE,
        5,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG018',
        'Poisoning/Drug Overdose',
        'MG',
        4000,
        4500,
        3500,
        FALSE,
        3,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG019',
        'Anemia requiring transfusion',
        'MG',
        3500,
        4000,
        3000,
        FALSE,
        2,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MG020',
        'Viral Hepatitis - Acute',
        'MG',
        4000,
        4500,
        3500,
        FALSE,
        5,
        FALSE,
        FALSE,
        '2.2'
    ) ON CONFLICT (code) DO
UPDATE
SET name = EXCLUDED.name,
    base_rate = EXCLUDED.base_rate,
    tier1_rate = EXCLUDED.tier1_rate,
    tier2_rate = EXCLUDED.tier2_rate;
-- ============================================
-- PACKAGES - Nephrology (Haemodialysis = 14% of claims)
-- ============================================
INSERT INTO pmjay_packages (
        code,
        name,
        specialty_code,
        base_rate,
        tier1_rate,
        tier2_rate,
        requires_preauth,
        expected_los,
        is_surgical,
        is_daycare,
        hbp_version
    )
VALUES (
        'NE001',
        'Haemodialysis (per session)',
        'NE',
        2000,
        2200,
        1800,
        FALSE,
        1,
        FALSE,
        TRUE,
        '2.2'
    ),
    (
        'NE002',
        'CAPD - Initial Setup with Training',
        'NE',
        40000,
        45000,
        35000,
        TRUE,
        7,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'NE003',
        'CAPD - Monthly Consumables',
        'NE',
        18000,
        20000,
        16000,
        FALSE,
        0,
        FALSE,
        TRUE,
        '2.2'
    ),
    (
        'NE004',
        'AV Fistula Creation',
        'NE',
        12000,
        14000,
        10000,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'NE005',
        'Permcath Insertion',
        'NE',
        15000,
        17000,
        13000,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'NE006',
        'Acute Kidney Injury - ICU Management',
        'NE',
        25000,
        28000,
        22000,
        TRUE,
        7,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'NE007',
        'Chronic Kidney Disease Management',
        'NE',
        5000,
        6000,
        4500,
        FALSE,
        4,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'NE008',
        'Kidney Biopsy',
        'NE',
        8000,
        9000,
        7000,
        TRUE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'NE009',
        'Peritoneal Dialysis - Acute',
        'NE',
        6000,
        7000,
        5500,
        FALSE,
        3,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'NE010',
        'Uremic Encephalopathy Management',
        'NE',
        12000,
        14000,
        10000,
        TRUE,
        5,
        FALSE,
        FALSE,
        '2.2'
    ) ON CONFLICT (code) DO
UPDATE
SET name = EXCLUDED.name,
    base_rate = EXCLUDED.base_rate;
-- ============================================
-- PACKAGES - Ophthalmology
-- ============================================
INSERT INTO pmjay_packages (
        code,
        name,
        specialty_code,
        base_rate,
        tier1_rate,
        tier2_rate,
        requires_preauth,
        expected_los,
        is_surgical,
        is_daycare,
        hbp_version
    )
VALUES (
        'OP001',
        'Cataract Surgery - SICS',
        'OP',
        10000,
        11000,
        9000,
        FALSE,
        1,
        TRUE,
        TRUE,
        '2.2'
    ),
    (
        'OP002',
        'Cataract Surgery - Phaco with foldable IOL',
        'OP',
        15000,
        17000,
        13000,
        FALSE,
        1,
        TRUE,
        TRUE,
        '2.2'
    ),
    (
        'OP003',
        'Pterygium Surgery',
        'OP',
        6000,
        7000,
        5500,
        FALSE,
        1,
        TRUE,
        TRUE,
        '2.2'
    ),
    (
        'OP004',
        'Dacryocystorhinostomy (DCR)',
        'OP',
        12000,
        14000,
        10000,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OP005',
        'Glaucoma Surgery - Trabeculectomy',
        'OP',
        15000,
        17000,
        13000,
        TRUE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OP006',
        'Retinal Detachment Surgery - SB',
        'OP',
        25000,
        28000,
        22000,
        TRUE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OP007',
        'Vitrectomy',
        'OP',
        35000,
        40000,
        30000,
        TRUE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OP008',
        'Squint Surgery - One Eye',
        'OP',
        12000,
        14000,
        10000,
        FALSE,
        1,
        TRUE,
        TRUE,
        '2.2'
    ),
    (
        'OP009',
        'Eyelid Surgery - Ptosis',
        'OP',
        10000,
        11000,
        9000,
        FALSE,
        1,
        TRUE,
        TRUE,
        '2.2'
    ),
    (
        'OP010',
        'Corneal Transplant',
        'OP',
        25000,
        28000,
        22000,
        TRUE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OP011',
        'Diabetic Retinopathy - Laser',
        'OP',
        5000,
        6000,
        4500,
        FALSE,
        1,
        FALSE,
        TRUE,
        '2.2'
    ),
    (
        'OP012',
        'Intravitreal Injection',
        'OP',
        8000,
        9000,
        7000,
        FALSE,
        1,
        FALSE,
        TRUE,
        '2.2'
    ) ON CONFLICT (code) DO
UPDATE
SET name = EXCLUDED.name,
    base_rate = EXCLUDED.base_rate;
-- ============================================
-- PACKAGES - Obstetrics & Gynaecology
-- ============================================
INSERT INTO pmjay_packages (
        code,
        name,
        specialty_code,
        base_rate,
        tier1_rate,
        tier2_rate,
        requires_preauth,
        expected_los,
        is_surgical,
        is_daycare,
        hbp_version
    )
VALUES (
        'OG001',
        'Normal Delivery',
        'OG',
        9000,
        10000,
        8000,
        FALSE,
        3,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'OG002',
        'Normal Delivery - Complicated',
        'OG',
        12000,
        14000,
        10000,
        FALSE,
        4,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'OG003',
        'Caesarean Section - LSCS',
        'OG',
        12000,
        14000,
        10000,
        FALSE,
        5,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OG004',
        'Caesarean Section - Complicated',
        'OG',
        18000,
        20000,
        16000,
        TRUE,
        7,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OG005',
        'MTP - First Trimester',
        'OG',
        4000,
        4500,
        3500,
        FALSE,
        1,
        TRUE,
        TRUE,
        '2.2'
    ),
    (
        'OG006',
        'MTP - Second Trimester',
        'OG',
        8000,
        9000,
        7000,
        TRUE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OG007',
        'Ectopic Pregnancy - Laparoscopic',
        'OG',
        18000,
        20000,
        16000,
        FALSE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OG008',
        'Ectopic Pregnancy - Open',
        'OG',
        12000,
        14000,
        10000,
        FALSE,
        4,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OG009',
        'Hysterectomy - Abdominal',
        'OG',
        20000,
        22000,
        18000,
        TRUE,
        5,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OG010',
        'Hysterectomy - Vaginal',
        'OG',
        18000,
        20000,
        16000,
        TRUE,
        4,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OG011',
        'Hysterectomy - Laparoscopic',
        'OG',
        25000,
        28000,
        22000,
        TRUE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OG012',
        'Ovarian Cyst - Laparoscopic',
        'OG',
        15000,
        17000,
        13000,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OG013',
        'Myomectomy',
        'OG',
        18000,
        20000,
        16000,
        TRUE,
        4,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OG014',
        'D&C - Diagnostic',
        'OG',
        3000,
        3500,
        2700,
        FALSE,
        1,
        TRUE,
        TRUE,
        '2.2'
    ),
    (
        'OG015',
        'Tubectomy - Postpartum',
        'OG',
        4000,
        4500,
        3500,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OG016',
        'Pre-eclampsia/Eclampsia Management',
        'OG',
        15000,
        17000,
        13000,
        TRUE,
        5,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'OG017',
        'PPH Management',
        'OG',
        18000,
        20000,
        16000,
        TRUE,
        5,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'OG018',
        'Vesicovaginal Fistula Repair',
        'OG',
        20000,
        22000,
        18000,
        TRUE,
        7,
        TRUE,
        FALSE,
        '2.2'
    ) ON CONFLICT (code) DO
UPDATE
SET name = EXCLUDED.name,
    base_rate = EXCLUDED.base_rate;
-- ============================================
-- PACKAGES - General Surgery
-- ============================================
INSERT INTO pmjay_packages (
        code,
        name,
        specialty_code,
        base_rate,
        tier1_rate,
        tier2_rate,
        requires_preauth,
        expected_los,
        is_surgical,
        is_daycare,
        hbp_version
    )
VALUES (
        'GS001',
        'Appendicectomy - Open',
        'GS',
        17000,
        19000,
        15000,
        FALSE,
        4,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS002',
        'Appendicectomy - Laparoscopic',
        'GS',
        25000,
        28000,
        22000,
        FALSE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS003',
        'Cholecystectomy - Open',
        'GS',
        18000,
        20000,
        16000,
        FALSE,
        5,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS004',
        'Cholecystectomy - Laparoscopic',
        'GS',
        25000,
        28000,
        22000,
        FALSE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS005',
        'Inguinal Hernia - Open',
        'GS',
        12000,
        14000,
        10000,
        FALSE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS006',
        'Inguinal Hernia - Laparoscopic (TAPP/TEP)',
        'GS',
        25000,
        28000,
        22000,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS007',
        'Umbilical Hernia Repair',
        'GS',
        10000,
        11000,
        9000,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS008',
        'Incisional Hernia Repair',
        'GS',
        18000,
        20000,
        16000,
        TRUE,
        4,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS009',
        'Hydrocele - Excision',
        'GS',
        8000,
        9000,
        7000,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS010',
        'Circumcision',
        'GS',
        3000,
        3500,
        2700,
        FALSE,
        1,
        TRUE,
        TRUE,
        '2.2'
    ),
    (
        'GS011',
        'Hemorrhoidectomy',
        'GS',
        8000,
        9000,
        7000,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS012',
        'Fistula-in-ano Surgery',
        'GS',
        10000,
        11000,
        9000,
        FALSE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS013',
        'Pilonidal Sinus Excision',
        'GS',
        8000,
        9000,
        7000,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS014',
        'Abscess I&D - Major',
        'GS',
        5000,
        6000,
        4500,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS015',
        'Lipoma Excision - Large',
        'GS',
        4000,
        4500,
        3500,
        FALSE,
        1,
        TRUE,
        TRUE,
        '2.2'
    ),
    (
        'GS016',
        'Sebaceous Cyst Excision',
        'GS',
        3000,
        3500,
        2700,
        FALSE,
        1,
        TRUE,
        TRUE,
        '2.2'
    ),
    (
        'GS017',
        'Varicose Veins - Stripping',
        'GS',
        15000,
        17000,
        13000,
        TRUE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS018',
        'Mastectomy - Simple',
        'GS',
        12000,
        14000,
        10000,
        TRUE,
        4,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS019',
        'Mastectomy - Modified Radical',
        'GS',
        20000,
        22000,
        18000,
        TRUE,
        5,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS020',
        'Thyroidectomy - Hemithyroidectomy',
        'GS',
        18000,
        20000,
        16000,
        TRUE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS021',
        'Thyroidectomy - Total',
        'GS',
        25000,
        28000,
        22000,
        TRUE,
        4,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS022',
        'Intestinal Obstruction - Emergency',
        'GS',
        25000,
        28000,
        22000,
        FALSE,
        7,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS023',
        'Perforated DU - Closure',
        'GS',
        20000,
        22000,
        18000,
        FALSE,
        7,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS024',
        'Splenectomy',
        'GS',
        25000,
        28000,
        22000,
        TRUE,
        5,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'GS025',
        'Colostomy Creation',
        'GS',
        15000,
        17000,
        13000,
        FALSE,
        7,
        TRUE,
        FALSE,
        '2.2'
    ) ON CONFLICT (code) DO
UPDATE
SET name = EXCLUDED.name,
    base_rate = EXCLUDED.base_rate;
-- ============================================
-- PACKAGES - Cardiology (High Value)
-- ============================================
INSERT INTO pmjay_packages (
        code,
        name,
        specialty_code,
        base_rate,
        tier1_rate,
        tier2_rate,
        requires_preauth,
        expected_los,
        is_surgical,
        is_daycare,
        hbp_version
    )
VALUES (
        'MC001',
        'Coronary Angiography - Diagnostic',
        'MC',
        12000,
        14000,
        10000,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC002',
        'PTCA - Single Stent (BMS)',
        'MC',
        45000,
        50000,
        40000,
        TRUE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC003',
        'PTCA - Single Stent (DES)',
        'MC',
        55000,
        60000,
        50000,
        TRUE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC004',
        'PTCA - Multiple Stents',
        'MC',
        75000,
        85000,
        65000,
        TRUE,
        4,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC005',
        'Permanent Pacemaker - Single Chamber',
        'MC',
        55000,
        60000,
        50000,
        TRUE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC006',
        'Permanent Pacemaker - Dual Chamber',
        'MC',
        85000,
        95000,
        75000,
        TRUE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC007',
        'CABG - Off Pump',
        'MC',
        120000,
        140000,
        100000,
        TRUE,
        10,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC008',
        'CABG - On Pump',
        'MC',
        150000,
        170000,
        130000,
        TRUE,
        12,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC009',
        'Mitral Valve Replacement',
        'MC',
        130000,
        150000,
        110000,
        TRUE,
        10,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC010',
        'Aortic Valve Replacement',
        'MC',
        140000,
        160000,
        120000,
        TRUE,
        10,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC011',
        'ASD Closure - Device',
        'MC',
        80000,
        90000,
        70000,
        TRUE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC012',
        'VSD Closure - Device',
        'MC',
        80000,
        90000,
        70000,
        TRUE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC013',
        'Acute MI - Thrombolysis',
        'MC',
        15000,
        17000,
        13000,
        FALSE,
        5,
        FALSE,
        FALSE,
        '2.2'
    ),
    (
        'MC014',
        'Pericardiocentesis',
        'MC',
        8000,
        9000,
        7000,
        FALSE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'MC015',
        'Temporary Pacemaker',
        'MC',
        12000,
        14000,
        10000,
        FALSE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ) ON CONFLICT (code) DO
UPDATE
SET name = EXCLUDED.name,
    base_rate = EXCLUDED.base_rate;
-- ============================================
-- PACKAGES - Orthopedics (Common)
-- ============================================
INSERT INTO pmjay_packages (
        code,
        name,
        specialty_code,
        base_rate,
        tier1_rate,
        tier2_rate,
        requires_preauth,
        expected_los,
        is_surgical,
        is_daycare,
        hbp_version
    )
VALUES (
        'OR001',
        'Fracture Shaft Femur - IM Nail',
        'OR',
        30000,
        35000,
        25000,
        TRUE,
        7,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR002',
        'Fracture Tibia - IM Nail',
        'OR',
        25000,
        28000,
        22000,
        TRUE,
        6,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR003',
        'Fracture both bones forearm - Plating',
        'OR',
        20000,
        22000,
        18000,
        FALSE,
        4,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR004',
        'Fracture Clavicle - Plating',
        'OR',
        15000,
        17000,
        13000,
        FALSE,
        3,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR005',
        'Fracture Neck of Femur - DHS',
        'OR',
        25000,
        28000,
        22000,
        TRUE,
        7,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR006',
        'Fracture Neck of Femur - Hemiarthroplasty',
        'OR',
        45000,
        50000,
        40000,
        TRUE,
        7,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR007',
        'Total Hip Replacement - Cemented',
        'OR',
        65000,
        75000,
        55000,
        TRUE,
        10,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR008',
        'Total Hip Replacement - Uncemented',
        'OR',
        80000,
        90000,
        70000,
        TRUE,
        10,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR009',
        'Total Knee Replacement - Single',
        'OR',
        80000,
        90000,
        70000,
        TRUE,
        10,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR010',
        'Total Knee Replacement - Bilateral',
        'OR',
        140000,
        160000,
        120000,
        TRUE,
        12,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR011',
        'ACL Reconstruction',
        'OR',
        40000,
        45000,
        35000,
        TRUE,
        4,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR012',
        'Meniscus Repair - Arthroscopic',
        'OR',
        25000,
        28000,
        22000,
        TRUE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR013',
        'Spinal Fusion - Single Level',
        'OR',
        80000,
        90000,
        70000,
        TRUE,
        7,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR014',
        'Laminectomy - Single Level',
        'OR',
        35000,
        40000,
        30000,
        TRUE,
        5,
        TRUE,
        FALSE,
        '2.2'
    ),
    (
        'OR015',
        'Implant Removal - Major',
        'OR',
        12000,
        14000,
        10000,
        FALSE,
        2,
        TRUE,
        FALSE,
        '2.2'
    ) ON CONFLICT (code) DO
UPDATE
SET name = EXCLUDED.name,
    base_rate = EXCLUDED.base_rate;
-- ============================================
-- INSERT PROCEDURES (Sample - linking to packages)
-- ============================================
INSERT INTO pmjay_procedures (
        code,
        name,
        package_code,
        specialty_code,
        rate,
        requires_preauth,
        includes_meds,
        includes_consumables,
        includes_diagnostics
    )
VALUES -- General Medicine Procedures
    (
        'MG001A',
        'Acute Febrile Illness Treatment',
        'MG001',
        'MG',
        1800,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'MG002A',
        'Acute Gastroenteritis Management',
        'MG002',
        'MG',
        2000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'MG003A',
        'Dengue Fever Moderate Treatment',
        'MG003',
        'MG',
        3000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'MG004A',
        'Dengue Hemorrhagic Fever Treatment',
        'MG004',
        'MG',
        8000,
        TRUE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'MG008A',
        'Community Acquired Pneumonia Treatment',
        'MG008',
        'MG',
        4000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'MG013A',
        'Diabetic Ketoacidosis Treatment',
        'MG013',
        'MG',
        8000,
        TRUE,
        TRUE,
        TRUE,
        TRUE
    ),
    -- Nephrology Procedures
    (
        'NE001A',
        'Haemodialysis Session',
        'NE001',
        'NE',
        2000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'NE004A',
        'Arteriovenous Fistula Creation',
        'NE004',
        'NE',
        12000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'NE005A',
        'Permcath Insertion',
        'NE005',
        'NE',
        15000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    -- Ophthalmology Procedures
    (
        'OP001A',
        'Cataract Surgery SICS with IOL',
        'OP001',
        'OP',
        10000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'OP002A',
        'Cataract Phacoemulsification with Foldable IOL',
        'OP002',
        'OP',
        15000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'OP005A',
        'Trabeculectomy for Glaucoma',
        'OP005',
        'OP',
        15000,
        TRUE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'OP007A',
        'Pars Plana Vitrectomy',
        'OP007',
        'OP',
        35000,
        TRUE,
        TRUE,
        TRUE,
        TRUE
    ),
    -- Obstetrics Procedures
    (
        'OG001A',
        'Normal Vaginal Delivery',
        'OG001',
        'OG',
        9000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'OG003A',
        'Lower Segment Caesarean Section',
        'OG003',
        'OG',
        12000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'OG004A',
        'Emergency Caesarean Section',
        'OG004',
        'OG',
        18000,
        TRUE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'OG009A',
        'Total Abdominal Hysterectomy',
        'OG009',
        'OG',
        20000,
        TRUE,
        TRUE,
        TRUE,
        TRUE
    ),
    -- General Surgery Procedures
    (
        'GS001A',
        'Open Appendicectomy',
        'GS001',
        'GS',
        17000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'GS002A',
        'Laparoscopic Appendicectomy',
        'GS002',
        'GS',
        25000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'GS003A',
        'Open Cholecystectomy',
        'GS003',
        'GS',
        18000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'GS004A',
        'Laparoscopic Cholecystectomy',
        'GS004',
        'GS',
        25000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'GS005A',
        'Open Inguinal Hernia Repair with Mesh',
        'GS005',
        'GS',
        12000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'GS006A',
        'Laparoscopic Inguinal Hernia Repair',
        'GS006',
        'GS',
        25000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    -- Cardiology Procedures
    (
        'MC001A',
        'Diagnostic Coronary Angiography',
        'MC001',
        'MC',
        12000,
        FALSE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'MC002A',
        'PTCA with Single BMS Stent',
        'MC002',
        'MC',
        45000,
        TRUE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'MC003A',
        'PTCA with Single DES Stent',
        'MC003',
        'MC',
        55000,
        TRUE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'MC007A',
        'CABG - Off Pump Triple Vessel',
        'MC007',
        'MC',
        120000,
        TRUE,
        TRUE,
        TRUE,
        TRUE
    ),
    -- Orthopedics Procedures
    (
        'OR001A',
        'Intramedullary Nailing Femur Shaft Fracture',
        'OR001',
        'OR',
        30000,
        TRUE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'OR006A',
        'Bipolar Hemiarthroplasty Hip',
        'OR006',
        'OR',
        45000,
        TRUE,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        'OR009A',
        'Total Knee Replacement Unilateral',
        'OR009',
        'OR',
        80000,
        TRUE,
        TRUE,
        TRUE,
        TRUE
    ) ON CONFLICT (code) DO
UPDATE
SET name = EXCLUDED.name,
    rate = EXCLUDED.rate;
-- Update procedure counts
UPDATE pmjay_specialties
SET procedure_count = (
        SELECT COUNT(*)
        FROM pmjay_procedures
        WHERE specialty_code = pmjay_specialties.code
    );
COMMIT;
-- Log seed completion
DO $$ BEGIN RAISE NOTICE 'PMJAY HBP 2.0 Seed Data Complete';
RAISE NOTICE 'Specialties: 23, Packages: ~85, Procedures: ~30 (priority sample)';
RAISE NOTICE 'Priority specialties seeded: MG, NE, OP, OG, GS, MC, OR';
END $$;