const axios = require('axios');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
const pool = require('../config/db');

const CLOUD_URL = 'https://wolf-tech-server-708086797390.asia-south1.run.app';
const SECRET = 'WolfHMS_Migration_Secret_2026';

async function recreateHospitals() {
    console.log('=== RECREATING HOSPITALS TABLE ===\n');
    
    try {
        // 1. Get Local Schema
        console.log('1. Fetching local schema...');
        const res = await pool.query(`
            SELECT column_name, data_type, character_maximum_length, is_nullable, column_default
            FROM information_schema.columns 
            WHERE table_name = 'hospitals'
        `);
        
        let createSql = `CREATE TABLE hospitals (\n`;
        const cols = [];
        res.rows.forEach(row => {
            let colDef = `${row.column_name} ${row.data_type}`;
            
            if (row.character_maximum_length) {
                colDef += `(${row.character_maximum_length})`;
            }
            
            if (row.column_name === 'id') {
                colDef += ' PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'; // Ensure BY DEFAULT
            } else {
                if (row.is_nullable === 'NO') colDef += ' NOT NULL';
                if (row.column_default) {
                    // Handle default values cautiously, strip ::type stuff
                    // But for simple texts/bools it's fine.
                    // For migration, removing defaults is often safer to avoid issues, 
                    // since we are inserting explicit values.
                    // colDef += ` DEFAULT ${row.column_default}`;
                }
            }
            cols.push(colDef);
        });
        
        createSql += cols.join(',\n');
        createSql += `\n);`;
        
        console.log('   Generated SQL:\n', createSql);

        // 2. Drop Cloud Table
        console.log('\n2. Dropping cloud table...');
        await axios.post(`${CLOUD_URL}/api/sync/sql`, {
            secret: SECRET,
            sql: `DROP TABLE IF EXISTS hospitals CASCADE;`
        });
        console.log('   ✅ Dropped hospitals');

        // 3. Create Cloud Table
        console.log('\n3. Creating cloud table...');
        await axios.post(`${CLOUD_URL}/api/sync/sql`, {
            secret: SECRET,
            sql: createSql
        });
        console.log('   ✅ Created hospitals');

    } catch (err) {
        console.error('Error:', err.message);
        if (err.response) console.log(JSON.stringify(err.response.data, null, 2));
    } finally {
        pool.end();
    }
}

recreateHospitals();
