const axios = require('axios');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
const pool = require('../config/db');

const CLOUD_URL = 'https://wolf-tech-server-708086797390.asia-south1.run.app';
const SECRET = 'WolfHMS_Migration_Secret_2026';

async function recreateUsers() {
    console.log('=== RECREATING USERS TABLE ===\n');
    
    try {
        // 1. Get Local Schema
        console.log('1. Fetching local schema...');
        const res = await pool.query(`
            SELECT column_name, data_type, character_maximum_length, is_nullable, column_default, udt_name
            FROM information_schema.columns 
            WHERE table_name = 'users'
        `);
        
        let createSql = `CREATE TABLE users (\n`;
        const cols = [];
        res.rows.forEach(row => {
            let type = row.data_type;
            
            // Handle Arrays
            if (type === 'ARRAY') {
                // udt_name usually starts with underscore for arrays, e.g. _text -> text[]
                type = row.udt_name.startsWith('_') ? row.udt_name.substring(1) + '[]' : 'text[]';
            }
            
            let colDef = `${row.column_name} ${type}`;
            
            if (row.character_maximum_length && !type.includes('[]')) {
                colDef += `(${row.character_maximum_length})`;
            }
            
            if (row.column_name === 'id') {
                colDef += ' PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY';
            } else {
                if (row.is_nullable === 'NO') colDef += ' NOT NULL';
            }
            cols.push(colDef);
        });
        
        createSql += cols.join(',\n');
        createSql += `\n);`;
        
        console.log('   Generated SQL:\n', createSql);

        // 2. Drop Cloud Table
        console.log('\n2. Dropping cloud table...');
        await axios.post(`${CLOUD_URL}/api/sync/sql`, {
            secret: SECRET,
            sql: `DROP TABLE IF EXISTS users CASCADE;`
        });
        console.log('   ✅ Dropped users');

        // 3. Create Cloud Table
        console.log('\n3. Creating cloud table...');
        try {
            await axios.post(`${CLOUD_URL}/api/sync/sql`, {
                secret: SECRET,
                sql: createSql
            });
            console.log('   ✅ Created users');
        } catch (e) {
            console.log('   ❌ Error creating users:', e.response?.data?.message || e.message);
            console.log('   Detail:', e.response?.data?.detail);
        }

    } catch (err) {
        console.error('Error:', err.message);
    } finally {
        pool.end();
    }
}

recreateUsers();
