const axios = require('axios');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
const pool = require('../config/db');

const CLOUD_URL = 'https://wolf-tech-server-708086797390.asia-south1.run.app';
const SECRET = 'WolfHMS_Migration_Secret_2026';

// Order matters for creation!
const TABLES = [
    'hospitals',
    'users',
    'patients',
    'wards',
    'beds',
    'admissions',
    'ot_rooms',
    'surgeries',
    'equipment_types',
    'ward_consumables',
    'ward_service_charges',
    'hospital_settings'
];

async function recreateAll() {
    console.log('=== RECREATING ALL TABLES ===\n');
    
    try {
        for (const table of TABLES) {
            console.log(`\nProcessing ${table}...`);
            
            // 1. Get Local Schema
            const res = await pool.query(`
                SELECT column_name, data_type, character_maximum_length, is_nullable, column_default, identity_generation
                FROM information_schema.columns 
                WHERE table_name = $1
            `, [table]);
            
            if (res.rows.length === 0) {
                console.log(`   ⚠️ Table ${table} not found locally! skipping.`);
                continue;
            }

            let createSql = `CREATE TABLE ${table} (\n`;
            const cols = [];
            
            // Collect primary keys to add constraint later if needed, 
            // but usually 'id PRIMARY KEY' inline is enough for single PK.
            
            res.rows.forEach(row => {
                let colDef = `${row.column_name} ${row.data_type}`;
                
                if (row.character_maximum_length) {
                    colDef += `(${row.character_maximum_length})`;
                }
                
                if (row.column_name === 'id') {
                    // Start primary key definition
                    colDef += ' PRIMARY KEY';
                    
                    // Handle identity/auto-increment
                    // Check if it's UUID or Integer
                    if (row.data_type === 'integer' || row.data_type === 'bigint') {
                        // For integer IDs, we usually want auto-increment
                        // Check if local has identity
                        // Force Generated By Default ensures we can insert our own IDs
                        colDef += ' GENERATED BY DEFAULT AS IDENTITY';
                    }
                    // For UUID, no identity needed (usually generated by client or default gen_random_uuid())
                } else {
                    if (row.is_nullable === 'NO') colDef += ' NOT NULL';
                    
                    // Defaults? Skipped to avoid issues with functions dependent on extensions (e.g. gen_random_uuid())
                    // unless we are sure. For sync, defaults aren't needed as we insert values.
                }
                cols.push(colDef);
            });
            
            createSql += cols.join(',\n');
            createSql += `\n);`;
            
            // 2. Drop Cloud Table
            try {
                await axios.post(`${CLOUD_URL}/api/sync/sql`, {
                    secret: SECRET,
                    sql: `DROP TABLE IF EXISTS ${table} CASCADE;`
                });
                console.log(`   🗑️ Dropped ${table} (Cascade)`);
            } catch (e) {
                console.log(`   ⚠️ Error dropping: ${e.message}`);
            }

            // 3. Create Cloud Table
            try {
                await axios.post(`${CLOUD_URL}/api/sync/sql`, {
                    secret: SECRET,
                    sql: createSql
                });
                console.log(`   ✨ Created ${table}`);
            } catch (e) {
                console.log(`   ❌ Error creating: ${e.message}`);
                console.log('   SQL:', createSql);
            }
        }

    } catch (err) {
        console.error('Fatal Error:', err.message);
    } finally {
        pool.end();
    }
}

recreateAll();
